In [1]:
# Useful starting lines
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
%load_ext autoreload
%autoreload 2

## Load the training data into feature matrix, class labels, and event ids:

In [2]:
from proj1_helpers import *
DATA_TRAIN_PATH = 'data/train.csv'
y, tX, ids = load_csv_data(DATA_TRAIN_PATH)

## Do your thing crazy machine learning thing here :) ...

In [27]:
from implementations import *

# columns with problems : 2 6 7 8 14 25 26 27 28 29 30   (all -2 for tX)

In [45]:
tX_cleaned = remove_wrong_columns(tX)
print(tX_cleaned)
degree = 2
tX_expanded = expand_features_polynomial(tX_cleaned, degree)
max_iters = 1000
initial_w = [0 for i in range(tX_expanded.shape[1])]
gamma = 0.0001

weights, loss = least_squares_SGD(y, tX_expanded, initial_w, max_iters, gamma)
print(weights)

[[ 138.47    51.655   97.827 ...    1.24    -2.475  113.497]
 [ 160.937   68.768  103.235 ... -999.    -999.      46.226]
 [-999.     162.172  125.953 ... -999.    -999.      44.251]
 ...
 [ 105.457   60.526   75.839 ... -999.    -999.      41.992]
 [  94.951   19.362   68.812 ... -999.    -999.       0.   ]
 [-999.      72.756   70.831 ... -999.    -999.       0.   ]]
[nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan]


## Generate predictions and save ouput in csv format for submission:

In [34]:
DATA_TEST_PATH = 'data/test.csv'
_, tX_test, ids_test = load_csv_data(DATA_TEST_PATH)

In [35]:
tX_test_cleaned = remove_wrong_columns(tX_test)
tX_test_expanded = expand_features_polynomial(tX_test_cleaned, degree)

In [36]:
OUTPUT_PATH = 'data/output.csv' 
y_pred = predict_labels(weights, tX_test_expanded)
create_csv_submission(ids_test, y_pred, OUTPUT_PATH)

/Users/samuel/EPFL/ML/Machine-learning/project1/proj1_helpers.py:30: RuntimeWarning: invalid value encountered in less_equal
  y_pred[np.where(y_pred <= 0)] = -1
/Users/samuel/EPFL/ML/Machine-learning/project1/proj1_helpers.py:31: RuntimeWarning: invalid value encountered in greater
  y_pred[np.where(y_pred > 0)] = 1


ValueError: cannot convert float NaN to integer