In [1]:
# Useful starting lines
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
%load_ext autoreload
%autoreload 2

## Load the training data into feature matrix, class labels, and event ids:

In [2]:
from proj1_helpers import *
DATA_TRAIN_PATH = 'data/train.csv'
y, tX, ids = load_csv_data(DATA_TRAIN_PATH)

## Do your thing crazy machine learning thing here :) ...

In [3]:
from implementations import *

# columns with problems : 2 6 7 8 14 25 26 27 28 29 30   (all -2 for tX)

In [7]:
tX_cleaned = remove_wrong_columns(tX)
print(tX_cleaned)
degree = 1
tX_expanded = expand_features_polynomial(tX_cleaned, degree)
max_iters = 100
initial_w = [0 for i in range(tX_expanded.shape[1])]
gamma = 0.0001

weights, loss = least_squares_SGD(y, tX_expanded, initial_w, max_iters, gamma)
print(weights)

[[ 51.655  97.827  27.98  ... 258.733   2.    113.497]
 [ 68.768 103.235  48.146 ... 164.546   1.     46.226]
 [162.172 125.953  35.635 ... 260.414   1.     44.251]
 ...
 [ 60.526  75.839  39.757 ... 198.907   1.     41.992]
 [ 19.362  68.812  13.504 ... 112.718   0.      0.   ]
 [ 72.756  70.831   7.479 ...  99.405   0.      0.   ]]
[ 0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.          0.          0.
  0.         -0.00310931 -0.00310931 -0.00310931 -0.00310931 -0.00310931
 -0.00310931 -0.00310931 -0.00310931 -0.00310931 -0.00310931 -0.00310931
 -0.00310931 -0.00310931 -0.00310931 -0.00310931 -0.00310931 -0.00310931
 -0.00310931 -0.00310931]


## Generate predictions and save ouput in csv format for submission:

In [8]:
DATA_TEST_PATH = 'data/test.csv'
_, tX_test, ids_test = load_csv_data(DATA_TEST_PATH)

In [9]:
tX_test_cleaned = remove_wrong_columns(tX_test)
tX_test_expanded = expand_features_polynomial(tX_test_cleaned, degree)

In [10]:
OUTPUT_PATH = 'data/output.csv' 
y_pred = predict_labels(weights, tX_test_expanded)
create_csv_submission(ids_test, y_pred, OUTPUT_PATH)